<template>
  <div v-if="props.showToggle" class="emoji-list-wrap" ref="emojiListWrap">
    <div class="emoji-list" v-on:click="btnClickEnventHandler">
      <button type="button" class="btn">😀</button>
      <button type="button" class="btn">😃</button>
      <button type="button" class="btn">😄</button>
      <button type="button" class="btn">😁</button>
      <button type="button" class="btn">😆</button>
      <button type="button" class="btn">😅</button>
      <button type="button" class="btn">🤣</button>
      <button type="button" class="btn">😂</button>
      <button type="button" class="btn">🙂</button>
      <button type="button" class="btn">🙃</button>
      <button type="button" class="btn">😉</button>
      <button type="button" class="btn">😊</button>
      <button type="button" class="btn">😇</button>
      <button type="button" class="btn">🥰</button>
      <button type="button" class="btn">😍</button>
      <button type="button" class="btn">🤩</button>
      <button type="button" class="btn">😘</button>
      <button type="button" class="btn">😗</button>
      <button type="button" class="btn">😚</button>
      <button type="button" class="btn">😙</button>
      <button type="button" class="btn">🥲</button>
      <button type="button" class="btn">😋</button>
      <button type="button" class="btn">😛</button>
      <button type="button" class="btn">😜</button>
      <button type="button" class="btn">🤪</button>
      <button type="button" class="btn">😝</button>
      <button type="button" class="btn">🤑</button>
      <button type="button" class="btn">🤗</button>
      <button type="button" class="btn">🤭</button>
      <button type="button" class="btn">🤫</button>
      <button type="button" class="btn">🤔</button>
      <button type="button" class="btn">🤐</button>
      <button type="button" class="btn">🤨</button>
      <button type="button" class="btn">😐</button>
      <button type="button" class="btn">😑</button>
      <button type="button" class="btn">😶</button>
      <button type="button" class="btn">😏</button>
      <button type="button" class="btn">😒</button>
      <button type="button" class="btn">🙄</button>
      <button type="button" class="btn">😬</button>
      <button type="button" class="btn">😮‍💨</button>
      <button type="button" class="btn">🤥</button>
      <button type="button" class="btn">😌</button>
      <button type="button" class="btn">😔</button>
      <button type="button" class="btn">😪</button>
      <button type="button" class="btn">🤤</button>
      <button type="button" class="btn">😴</button>
      <button type="button" class="btn">😷</button>
      <button type="button" class="btn">🤒</button>
      <button type="button" class="btn">🤕</button>
      <button type="button" class="btn">🤢</button>
      <button type="button" class="btn">🤮</button>
      <button type="button" class="btn">🤧</button>
      <button type="button" class="btn">🥵</button>
      <button type="button" class="btn">🥶</button>
      <button type="button" class="btn">🥴</button>
      <button type="button" class="btn">😵</button>
      <button type="button" class="btn">😵‍💫</button>
      <button type="button" class="btn">🤯</button>
      <button type="button" class="btn">🤠</button>
      <button type="button" class="btn">🥳</button>
      <button type="button" class="btn">🥸</button>
      <button type="button" class="btn">😎</button>
      <button type="button" class="btn">🤓</button>
      <button type="button" class="btn">🧐</button>
      <button type="button" class="btn">😕</button>
      <button type="button" class="btn">😟</button>
      <button type="button" class="btn">🙁</button>
      <button type="button" class="btn">😮</button>
      <button type="button" class="btn">😯</button>
      <button type="button" class="btn">😲</button>
      <button type="button" class="btn">😳</button>
      <button type="button" class="btn">🥺</button>
      <button type="button" class="btn">😦</button>
      <button type="button" class="btn">😧</button>
      <button type="button" class="btn">😨</button>
      <button type="button" class="btn">😰</button>
      <button type="button" class="btn">😥</button>
      <button type="button" class="btn">😢</button>
      <button type="button" class="btn">😭</button>
      <button type="button" class="btn">😱</button>
      <button type="button" class="btn">😖</button>
      <button type="button" class="btn">😣</button>
      <button type="button" class="btn">😞</button>
      <button type="button" class="btn">😓</button>
      <button type="button" class="btn">😩</button>
      <button type="button" class="btn">😫</button>
      <button type="button" class="btn">🥱</button>
      <button type="button" class="btn">😤</button>
      <button type="button" class="btn">😡</button>
      <button type="button" class="btn">😠</button>
      <button type="button" class="btn">🤬</button>
      <button type="button" class="btn">😈</button>
      <button type="button" class="btn">👿</button>
      <button type="button" class="btn">💀</button>
      <button type="button" class="btn">☠</button>
      <button type="button" class="btn">💩</button>
      <button type="button" class="btn">🤡</button>
      <button type="button" class="btn">👹</button>
      <button type="button" class="btn">👺</button>
      <button type="button" class="btn">👻</button>
      <button type="button" class="btn">👽</button>
      <button type="button" class="btn">👾</button>
      <button type="button" class="btn">🤖</button>
      <button type="button" class="btn">😺</button>
      <button type="button" class="btn">😸</button>
      <button type="button" class="btn">😹</button>
      <button type="button" class="btn">😻</button>
      <button type="button" class="btn">😼</button>
      <button type="button" class="btn">😽</button>
      <button type="button" class="btn">🙀</button>
      <button type="button" class="btn">😿</button>
      <button type="button" class="btn">😾</button>
      <button type="button" class="btn">🙈</button>
      <button type="button" class="btn">🙉</button>
      <button type="button" class="btn">🙊</button>

      <hr />
      <button type="button" class="btn">💋</button>
      <button type="button" class="btn">💌</button>
      <button type="button" class="btn">💘</button>
      <button type="button" class="btn">💝</button>
      <button type="button" class="btn">💖</button>
      <button type="button" class="btn">💗</button>
      <button type="button" class="btn">💓</button>
      <button type="button" class="btn">💞</button>
      <button type="button" class="btn">💕</button>
      <button type="button" class="btn">💟</button>
      <button type="button" class="btn">❣</button>
      <button type="button" class="btn">💔</button>
      <button type="button" class="btn">❤</button>
      <button type="button" class="btn">🧡</button>
      <button type="button" class="btn">💛</button>
      <button type="button" class="btn">💚</button>
      <button type="button" class="btn">💙</button>
      <button type="button" class="btn">💜</button>
      <button type="button" class="btn">🤎</button>
      <button type="button" class="btn">🖤</button>
      <button type="button" class="btn">🤍</button>
      <button type="button" class="btn">💯</button>
      <button type="button" class="btn">💢</button>
      <button type="button" class="btn">💥</button>
      <button type="button" class="btn">💫</button>
      <button type="button" class="btn">💦</button>
      <button type="button" class="btn">💨</button>
      <button type="button" class="btn">🕳</button>
      <button type="button" class="btn">💣</button>
      <button type="button" class="btn">💬</button>
      <button type="button" class="btn">🗨</button>
      <button type="button" class="btn">🗯</button>
      <button type="button" class="btn">💭</button>
      <button type="button" class="btn">💤</button>
      <hr />
      <button type="button" class="btn">👋</button>
      <button type="button" class="btn">🤚</button>
      <button type="button" class="btn">🖐</button>
      <button type="button" class="btn">✋</button>
      <button type="button" class="btn">🖖</button>
      <button type="button" class="btn">👌</button>
      <button type="button" class="btn">🤌</button>
      <button type="button" class="btn">🤏</button>
      <button type="button" class="btn">✌</button>
      <button type="button" class="btn">🤞</button>
      <button type="button" class="btn">🤟</button>
      <button type="button" class="btn">🤘</button>
      <button type="button" class="btn">🤙</button>
      <button type="button" class="btn">👈</button>
      <button type="button" class="btn">👉</button>
      <button type="button" class="btn">👆</button>
      <button type="button" class="btn">🖕</button>
      <button type="button" class="btn">👇</button>
      <button type="button" class="btn">☝</button>
      <button type="button" class="btn">👍</button>
      <button type="button" class="btn">👎</button>
      <button type="button" class="btn">✊</button>
      <button type="button" class="btn">👊</button>
      <button type="button" class="btn">🤛</button>
      <button type="button" class="btn">🤜</button>
      <button type="button" class="btn">👏</button>
      <button type="button" class="btn">🙌</button>
      <button type="button" class="btn">👐</button>
      <button type="button" class="btn">🤲</button>
      <button type="button" class="btn">🤝</button>
      <button type="button" class="btn">🙏</button>
      <button type="button" class="btn">✍</button>
      <button type="button" class="btn">💅</button>
      <button type="button" class="btn">🤳</button>
      <button type="button" class="btn">💪</button>
      <button type="button" class="btn">🦾</button>
      <button type="button" class="btn">🦿</button>
      <button type="button" class="btn">🦵</button>
      <button type="button" class="btn">🦶</button>
      <button type="button" class="btn">👂</button>
      <button type="button" class="btn">🦻</button>
      <button type="button" class="btn">👃</button>
      <button type="button" class="btn">🧠</button>
      <button type="button" class="btn">🫀</button>
      <button type="button" class="btn">🫁</button>
      <button type="button" class="btn">🦷</button>
      <button type="button" class="btn">🦴</button>
      <button type="button" class="btn">👀</button>
      <button type="button" class="btn">👁</button>
      <button type="button" class="btn">👅</button>
      <button type="button" class="btn">👄</button>
      <hr />
      <button type="button" class="btn">👶</button>
      <button type="button" class="btn">🧒</button>
      <button type="button" class="btn">👦</button>
      <button type="button" class="btn">👧</button>
      <button type="button" class="btn">🧑</button>
      <button type="button" class="btn">👱</button>
      <button type="button" class="btn">👨</button>
      <button type="button" class="btn">🧔</button>
      <button type="button" class="btn">👩</button>
      <button type="button" class="btn">🧓</button>
      <button type="button" class="btn">👴</button>
      <button type="button" class="btn">👵</button>
      <button type="button" class="btn">🙍</button>
      <button type="button" class="btn">🙎</button>
      <button type="button" class="btn">🙅</button>
      <button type="button" class="btn">🙆</button>
      <button type="button" class="btn">💁</button>
      <button type="button" class="btn">🙋</button>
      <button type="button" class="btn">🧏</button>
      <button type="button" class="btn">🙇</button>
      <button type="button" class="btn">🤦</button>
      <button type="button" class="btn">🤷</button>
      <button type="button" class="btn">🧑‍🎓</button>
      <button type="button" class="btn">👨‍🎓</button>
      <button type="button" class="btn">👩‍🎓</button>
      <button type="button" class="btn">🧑‍🏫</button>
      <button type="button" class="btn">👨‍🏫</button>
      <button type="button" class="btn">👩‍🏫</button>
      <button type="button" class="btn">🧑‍🌾</button>
      <button type="button" class="btn">👨‍🌾</button>
      <button type="button" class="btn">👩‍🌾</button>
      <button type="button" class="btn">🧑‍🍳</button>
      <button type="button" class="btn">👨‍🍳</button>
      <button type="button" class="btn">👩‍🍳</button>
      <button type="button" class="btn">🧑‍🔧</button>
      <button type="button" class="btn">👨‍🔧</button>
      <button type="button" class="btn">👩‍🔧</button>
      <button type="button" class="btn">🧑‍🏭</button>
      <button type="button" class="btn">👨‍🏭</button>
      <button type="button" class="btn">👩‍🏭</button>
      <button type="button" class="btn">🧑‍💼</button>
      <button type="button" class="btn">👨‍💼</button>
      <button type="button" class="btn">👩‍💼</button>
      <button type="button" class="btn">🧑‍🔬</button>
      <button type="button" class="btn">👨‍🔬</button>
      <button type="button" class="btn">👩‍🔬</button>
      <button type="button" class="btn">🧑‍💻</button>
      <button type="button" class="btn">👨‍💻</button>
      <button type="button" class="btn">👩‍💻</button>
      <button type="button" class="btn">🧑‍🎤</button>
      <button type="button" class="btn">👨‍🎤</button>
      <button type="button" class="btn">👩‍🎤</button>
      <button type="button" class="btn">🧑‍🎨</button>
      <button type="button" class="btn">👨‍🎨</button>
      <button type="button" class="btn">👩‍🎨</button>
      <button type="button" class="btn">🧑‍🚀</button>
      <button type="button" class="btn">👨‍🚀</button>
      <button type="button" class="btn">👩‍🚀</button>
      <button type="button" class="btn">🧑‍🚒</button>
      <button type="button" class="btn">👨‍🚒</button>
      <button type="button" class="btn">👩‍🚒</button>
      <button type="button" class="btn">👮</button>
      <button type="button" class="btn">🕵</button>
      <button type="button" class="btn">💂</button>
      <button type="button" class="btn">🥷</button>
      <button type="button" class="btn">👷</button>
      <button type="button" class="btn">🤴</button>
      <button type="button" class="btn">👸</button>
      <button type="button" class="btn">👳</button>
      <button type="button" class="btn">👲</button>
      <button type="button" class="btn">🧕</button>
      <button type="button" class="btn">🤵</button>
      <button type="button" class="btn">👰</button>
      <button type="button" class="btn">🤰</button>
      <button type="button" class="btn">🤱</button>
      <button type="button" class="btn">👩‍🍼</button>
      <button type="button" class="btn">👨‍🍼</button>
      <button type="button" class="btn">🧑‍🍼</button>
      <button type="button" class="btn">👼</button>
      <button type="button" class="btn">🎅</button>
      <button type="button" class="btn">🤶</button>
      <button type="button" class="btn">🧑‍🎄</button>
      <button type="button" class="btn">🦸</button>
      <button type="button" class="btn">🦹</button>
      <button type="button" class="btn">🧙</button>
      <button type="button" class="btn">🧚</button>
      <button type="button" class="btn">🧛</button>
      <button type="button" class="btn">🧜</button>
      <button type="button" class="btn">🧝</button>
      <button type="button" class="btn">🧞</button>
      <button type="button" class="btn">🧟</button>
      <button type="button" class="btn">💆</button>
      <button type="button" class="btn">💇</button>
      <button type="button" class="btn">🚶</button>
      <button type="button" class="btn">🧍</button>
      <button type="button" class="btn">🧎</button>
      <button type="button" class="btn">🧑‍🦯</button>
      <button type="button" class="btn">👨‍🦯</button>
      <button type="button" class="btn">👩‍🦯</button>
      <button type="button" class="btn">🧑‍🦼</button>
      <button type="button" class="btn">👨‍🦼</button>
      <button type="button" class="btn">👩‍🦼</button>
      <button type="button" class="btn">🧑‍🦽</button>
      <button type="button" class="btn">👨‍🦽</button>
      <button type="button" class="btn">👩‍🦽</button>
      <button type="button" class="btn">🏃</button>
      <button type="button" class="btn">💃</button>
      <button type="button" class="btn">🕺</button>
      <button type="button" class="btn">🕴</button>
      <button type="button" class="btn">👯</button>
      <button type="button" class="btn">🧖</button>
      <button type="button" class="btn">🧗</button>
      <button type="button" class="btn">🤺</button>
      <button type="button" class="btn">🏇</button>
      <button type="button" class="btn">⛷</button>
      <button type="button" class="btn">🏂</button>
      <button type="button" class="btn">🏌</button>
      <button type="button" class="btn">🏄</button>
      <button type="button" class="btn">🚣</button>
      <button type="button" class="btn">🏊</button>
      <button type="button" class="btn">⛹</button>
      <button type="button" class="btn">🏋</button>
      <button type="button" class="btn">🚴</button>
      <button type="button" class="btn">🚵</button>
      <button type="button" class="btn">🤸</button>
      <button type="button" class="btn">🤼</button>
      <button type="button" class="btn">🤽</button>
      <button type="button" class="btn">🤾</button>
      <button type="button" class="btn">🤹</button>
      <button type="button" class="btn">🧘</button>
      <button type="button" class="btn">🛀</button>
      <button type="button" class="btn">🛌</button>
      <button type="button" class="btn">🧑‍🤝‍🧑</button>
      <button type="button" class="btn">👭</button>
      <button type="button" class="btn">👫</button>
      <button type="button" class="btn">👬</button>
      <button type="button" class="btn">💏</button>
      <button type="button" class="btn">💑</button>
      <button type="button" class="btn">👪</button>
      <button type="button" class="btn">🗣</button>
      <button type="button" class="btn">👤</button>
      <button type="button" class="btn">👥</button>
      <button type="button" class="btn">🫂</button>
      <button type="button" class="btn">👣</button>
      <button type="button" class="btn">🦰</button>
      <button type="button" class="btn">🦱</button>
      <button type="button" class="btn">🦳</button>
      <button type="button" class="btn">🦲</button>
      <hr />
      <button type="button" class="btn">🐵</button>
      <button type="button" class="btn">🐒</button>
      <button type="button" class="btn">🦍</button>
      <button type="button" class="btn">🦧</button>
      <button type="button" class="btn">🐶</button>
      <button type="button" class="btn">🐕</button>
      <button type="button" class="btn">🦮</button>
      <button type="button" class="btn">🐕‍🦺</button>
      <button type="button" class="btn">🐩</button>
      <button type="button" class="btn">🐺</button>
      <button type="button" class="btn">🦊</button>
      <button type="button" class="btn">🦝</button>
      <button type="button" class="btn">🐱</button>
      <button type="button" class="btn">🐈</button>
      <button type="button" class="btn">🐈‍⬛</button>
      <button type="button" class="btn">🦁</button>
      <button type="button" class="btn">🐯</button>
      <button type="button" class="btn">🐅</button>
      <button type="button" class="btn">🐆</button>
      <button type="button" class="btn">🐴</button>
      <button type="button" class="btn">🐎</button>
      <button type="button" class="btn">🦄</button>
      <button type="button" class="btn">🦓</button>
      <button type="button" class="btn">🦌</button>
      <button type="button" class="btn">🦬</button>
      <button type="button" class="btn">🐮</button>
      <button type="button" class="btn">🐂</button>
      <button type="button" class="btn">🐃</button>
      <button type="button" class="btn">🐄</button>
      <button type="button" class="btn">🐷</button>
      <button type="button" class="btn">🐖</button>
      <button type="button" class="btn">🐗</button>
      <button type="button" class="btn">🐽</button>
      <button type="button" class="btn">🐏</button>
      <button type="button" class="btn">🐑</button>
      <button type="button" class="btn">🐐</button>
      <button type="button" class="btn">🐪</button>
      <button type="button" class="btn">🐫</button>
      <button type="button" class="btn">🦙</button>
      <button type="button" class="btn">🦒</button>
      <button type="button" class="btn">🐘</button>
      <button type="button" class="btn">🦣</button>
      <button type="button" class="btn">🦏</button>
      <button type="button" class="btn">🦛</button>
      <button type="button" class="btn">🐭</button>
      <button type="button" class="btn">🐁</button>
      <button type="button" class="btn">🐀</button>
      <button type="button" class="btn">🐹</button>
      <button type="button" class="btn">🐰</button>
      <button type="button" class="btn">🐇</button>
      <button type="button" class="btn">🐿</button>
      <button type="button" class="btn">🦫</button>
      <button type="button" class="btn">🦔</button>
      <button type="button" class="btn">🦇</button>
      <button type="button" class="btn">🐻</button>
      <button type="button" class="btn">🐨</button>
      <button type="button" class="btn">🐼</button>
      <button type="button" class="btn">🦥</button>
      <button type="button" class="btn">🦦</button>
      <button type="button" class="btn">🦨</button>
      <button type="button" class="btn">🦘</button>
      <button type="button" class="btn">🦡</button>
      <button type="button" class="btn">🐾</button>
      <button type="button" class="btn">🦃</button>
      <button type="button" class="btn">🐔</button>
      <button type="button" class="btn">🐓</button>
      <button type="button" class="btn">🐣</button>
      <button type="button" class="btn">🐤</button>
      <button type="button" class="btn">🐥</button>
      <button type="button" class="btn">🐦</button>
      <button type="button" class="btn">🐧</button>
      <button type="button" class="btn">🕊</button>
      <button type="button" class="btn">🦅</button>
      <button type="button" class="btn">🦆</button>
      <button type="button" class="btn">🦢</button>
      <button type="button" class="btn">🦉</button>
      <button type="button" class="btn">🦤</button>
      <button type="button" class="btn">🪶</button>
      <button type="button" class="btn">🦩</button>
      <button type="button" class="btn">🦚</button>
      <button type="button" class="btn">🦜</button>
      <button type="button" class="btn">🐸</button>
      <button type="button" class="btn">🐊</button>
      <button type="button" class="btn">🐢</button>
      <button type="button" class="btn">🦎</button>
      <button type="button" class="btn">🐍</button>
      <button type="button" class="btn">🐲</button>
      <button type="button" class="btn">🐉</button>
      <button type="button" class="btn">🦕</button>
      <button type="button" class="btn">🦖</button>
      <button type="button" class="btn">🐳</button>
      <button type="button" class="btn">🐋</button>
      <button type="button" class="btn">🐬</button>
      <button type="button" class="btn">🦭</button>
      <button type="button" class="btn">🐟</button>
      <button type="button" class="btn">🐠</button>
      <button type="button" class="btn">🐡</button>
      <button type="button" class="btn">🦈</button>
      <button type="button" class="btn">🐙</button>
      <button type="button" class="btn">🐚</button>
      <button type="button" class="btn">🐌</button>
      <button type="button" class="btn">🦋</button>
      <button type="button" class="btn">🐛</button>
      <button type="button" class="btn">🐜</button>
      <button type="button" class="btn">🐝</button>
      <button type="button" class="btn">🪲</button>
      <button type="button" class="btn">🐞</button>
      <button type="button" class="btn">🦗</button>
      <button type="button" class="btn">🪳</button>
      <button type="button" class="btn">🕷</button>
      <button type="button" class="btn">🕸</button>
      <button type="button" class="btn">🦂</button>
      <button type="button" class="btn">🦟</button>
      <button type="button" class="btn">🪰</button>
      <button type="button" class="btn">🪱</button>
      <button type="button" class="btn">🦠</button>
      <hr />
      <button type="button" class="btn">💐</button>
      <button type="button" class="btn">🌸</button>
      <button type="button" class="btn">💮</button>
      <button type="button" class="btn">🌹</button>
      <button type="button" class="btn">🥀</button>
      <button type="button" class="btn">🌺</button>
      <button type="button" class="btn">🌻</button>
      <button type="button" class="btn">🌼</button>
      <button type="button" class="btn">🌷</button>
      <button type="button" class="btn">🌱</button>
      <button type="button" class="btn">🪴</button>
      <button type="button" class="btn">🌲</button>
      <button type="button" class="btn">🌳</button>
      <button type="button" class="btn">🌴</button>
      <button type="button" class="btn">🌵</button>
      <button type="button" class="btn">🌾</button>
      <button type="button" class="btn">🌿</button>
      <button type="button" class="btn">🍀</button>
      <button type="button" class="btn">🍁</button>
      <button type="button" class="btn">🍂</button>
      <button type="button" class="btn">🍃</button>
      <button type="button" class="btn">🍇</button>
      <button type="button" class="btn">🍈</button>
      <button type="button" class="btn">🍉</button>
      <button type="button" class="btn">🍊</button>
      <button type="button" class="btn">🍋</button>
      <button type="button" class="btn">🍌</button>
      <button type="button" class="btn">🍍</button>
      <button type="button" class="btn">🥭</button>
      <button type="button" class="btn">🍎</button>
      <button type="button" class="btn">🍏</button>
      <button type="button" class="btn">🍐</button>
      <button type="button" class="btn">🍑</button>
      <button type="button" class="btn">🍒</button>
      <button type="button" class="btn">🍓</button>
      <button type="button" class="btn">🫐</button>
      <button type="button" class="btn">🥝</button>
      <button type="button" class="btn">🍅</button>
      <button type="button" class="btn">🫒</button>
      <button type="button" class="btn">🥥</button>
      <button type="button" class="btn">🥑</button>
      <button type="button" class="btn">🍆</button>
      <button type="button" class="btn">🥔</button>
      <button type="button" class="btn">🥕</button>
      <button type="button" class="btn">🌽</button>
      <button type="button" class="btn">🫑</button>
      <button type="button" class="btn">🥒</button>
      <button type="button" class="btn">🥬</button>
      <button type="button" class="btn">🥦</button>
      <button type="button" class="btn">🧄</button>
      <button type="button" class="btn">🧅</button>
      <button type="button" class="btn">🍄</button>
      <button type="button" class="btn">🥜</button>
      <button type="button" class="btn">🌰</button>
      <button type="button" class="btn">🍞</button>
      <button type="button" class="btn">🥐</button>
      <button type="button" class="btn">🥖</button>
      <button type="button" class="btn">🫓</button>
      <button type="button" class="btn">🥨</button>
      <button type="button" class="btn">🥯</button>
      <button type="button" class="btn">🥞</button>
      <button type="button" class="btn">🧇</button>
      <button type="button" class="btn">🧀</button>
      <button type="button" class="btn">🍖</button>
      <button type="button" class="btn">🍗</button>
      <button type="button" class="btn">🥩</button>
      <button type="button" class="btn">🥓</button>
      <button type="button" class="btn">🍔</button>
      <button type="button" class="btn">🍟</button>
      <button type="button" class="btn">🍕</button>
      <button type="button" class="btn">🌭</button>
      <button type="button" class="btn">🥪</button>
      <button type="button" class="btn">🌮</button>
      <button type="button" class="btn">🌯</button>
      <button type="button" class="btn">🫔</button>
      <button type="button" class="btn">🥙</button>
      <button type="button" class="btn">🧆</button>
      <button type="button" class="btn">🥚</button>
      <button type="button" class="btn">🍳</button>
      <button type="button" class="btn">🥘</button>
      <button type="button" class="btn">🍲</button>
      <button type="button" class="btn">🫕</button>
      <button type="button" class="btn">🥣</button>
      <button type="button" class="btn">🥗</button>
      <button type="button" class="btn">🍿</button>
      <button type="button" class="btn">🧈</button>
      <button type="button" class="btn">🧂</button>
      <button type="button" class="btn">🥫</button>
      <button type="button" class="btn">🍱</button>
      <button type="button" class="btn">🍘</button>
      <button type="button" class="btn">🍙</button>
      <button type="button" class="btn">🍚</button>
      <button type="button" class="btn">🍛</button>
      <button type="button" class="btn">🍜</button>
      <button type="button" class="btn">🍝</button>
      <button type="button" class="btn">🍠</button>
      <button type="button" class="btn">🍢</button>
      <button type="button" class="btn">🍣</button>
      <button type="button" class="btn">🍤</button>
      <button type="button" class="btn">🍥</button>
      <button type="button" class="btn">🥮</button>
      <button type="button" class="btn">🍡</button>
      <button type="button" class="btn">🥟</button>
      <button type="button" class="btn">🥠</button>
      <button type="button" class="btn">🥡</button>
      <button type="button" class="btn">🦀</button>
      <button type="button" class="btn">🦞</button>
      <button type="button" class="btn">🦐</button>
      <button type="button" class="btn">🦑</button>
      <button type="button" class="btn">🦪</button>
      <button type="button" class="btn">🍦</button>
      <button type="button" class="btn">🍧</button>
      <button type="button" class="btn">🍨</button>
      <button type="button" class="btn">🍩</button>
      <button type="button" class="btn">🍪</button>
      <button type="button" class="btn">🎂</button>
      <button type="button" class="btn">🍰</button>
      <button type="button" class="btn">🧁</button>
      <button type="button" class="btn">🥧</button>
      <button type="button" class="btn">🍫</button>
      <button type="button" class="btn">🍬</button>
      <button type="button" class="btn">🍭</button>
      <button type="button" class="btn">🍮</button>
      <button type="button" class="btn">🍯</button>
      <button type="button" class="btn">🍼</button>
      <button type="button" class="btn">🥛</button>
      <button type="button" class="btn">☕</button>
      <button type="button" class="btn">🫖</button>
      <button type="button" class="btn">🍵</button>
      <button type="button" class="btn">🍶</button>
      <button type="button" class="btn">🍾</button>
      <button type="button" class="btn">🍷</button>
      <button type="button" class="btn">🍸</button>
      <button type="button" class="btn">🍹</button>
      <button type="button" class="btn">🍺</button>
      <button type="button" class="btn">🍻</button>
      <button type="button" class="btn">🥂</button>
      <button type="button" class="btn">🥃</button>
      <button type="button" class="btn">🥤</button>
      <button type="button" class="btn">🧋</button>
      <button type="button" class="btn">🧃</button>
      <button type="button" class="btn">🧉</button>
      <button type="button" class="btn">🧊</button>
      <button type="button" class="btn">🥢</button>
      <button type="button" class="btn">🍽</button>
      <button type="button" class="btn">🍴</button>
      <button type="button" class="btn">🥄</button>
      <button type="button" class="btn">🔪</button>
      <button type="button" class="btn">🏺</button>
      <button type="button" class="btn">🌍</button>
      <button type="button" class="btn">🌎</button>
      <button type="button" class="btn">🌏</button>
      <button type="button" class="btn">🌐</button>
      <button type="button" class="btn">🗺</button>
      <button type="button" class="btn">🗾</button>
      <button type="button" class="btn">🧭</button>
      <button type="button" class="btn">🏔</button>
      <button type="button" class="btn">⛰</button>
      <button type="button" class="btn">🌋</button>
      <button type="button" class="btn">🗻</button>
      <button type="button" class="btn">🏕</button>
      <button type="button" class="btn">🏖</button>
      <button type="button" class="btn">🏜</button>
      <button type="button" class="btn">🏝</button>
      <button type="button" class="btn">🏞</button>
      <button type="button" class="btn">🏟</button>
      <button type="button" class="btn">🏛</button>
      <button type="button" class="btn">🏗</button>
      <button type="button" class="btn">🧱</button>
      <button type="button" class="btn">🪨</button>
      <button type="button" class="btn">🪵</button>
      <button type="button" class="btn">🛖</button>
      <button type="button" class="btn">🏘</button>
      <button type="button" class="btn">🏚</button>
      <button type="button" class="btn">🏠</button>
      <button type="button" class="btn">🏡</button>
      <button type="button" class="btn">🏢</button>
      <button type="button" class="btn">🏣</button>
      <button type="button" class="btn">🏤</button>
      <button type="button" class="btn">🏥</button>
      <button type="button" class="btn">🏦</button>
      <button type="button" class="btn">🏨</button>
      <button type="button" class="btn">🏩</button>
      <button type="button" class="btn">🏪</button>
      <button type="button" class="btn">🏫</button>
      <button type="button" class="btn">🏬</button>
      <button type="button" class="btn">🏭</button>
      <button type="button" class="btn">🏯</button>
      <button type="button" class="btn">🏰</button>
      <button type="button" class="btn">💒</button>
      <button type="button" class="btn">🗼</button>
      <button type="button" class="btn">🗽</button>
      <button type="button" class="btn">⛪</button>
      <button type="button" class="btn">🕌</button>
      <button type="button" class="btn">🛕</button>
      <button type="button" class="btn">🕍</button>
      <button type="button" class="btn">⛩</button>
      <button type="button" class="btn">🕋</button>
      <button type="button" class="btn">⛲</button>
      <button type="button" class="btn">⛺</button>
      <button type="button" class="btn">🌁</button>
      <button type="button" class="btn">🌃</button>
      <button type="button" class="btn">🏙</button>
      <button type="button" class="btn">🌄</button>
      <button type="button" class="btn">🌅</button>
      <button type="button" class="btn">🌆</button>
      <button type="button" class="btn">🌇</button>
      <button type="button" class="btn">🌉</button>
      <button type="button" class="btn">♨</button>
      <button type="button" class="btn">🎠</button>
      <button type="button" class="btn">🎡</button>
      <button type="button" class="btn">🎢</button>
      <button type="button" class="btn">💈</button>
      <button type="button" class="btn">🎪</button>
      <button type="button" class="btn">🚂</button>
      <button type="button" class="btn">🚃</button>
      <button type="button" class="btn">🚄</button>
      <button type="button" class="btn">🚅</button>
      <button type="button" class="btn">🚆</button>
      <button type="button" class="btn">🚇</button>
      <button type="button" class="btn">🚈</button>
      <button type="button" class="btn">🚉</button>
      <button type="button" class="btn">🚊</button>
      <button type="button" class="btn">🚝</button>
      <button type="button" class="btn">🚞</button>
      <button type="button" class="btn">🚋</button>
      <button type="button" class="btn">🚌</button>
      <button type="button" class="btn">🚍</button>
      <button type="button" class="btn">🚎</button>
      <button type="button" class="btn">🚐</button>
      <button type="button" class="btn">🚑</button>
      <button type="button" class="btn">🚒</button>
      <button type="button" class="btn">🚓</button>
      <button type="button" class="btn">🚔</button>
      <button type="button" class="btn">🚕</button>
      <button type="button" class="btn">🚖</button>
      <button type="button" class="btn">🚗</button>
      <button type="button" class="btn">🚘</button>
      <button type="button" class="btn">🚙</button>
      <button type="button" class="btn">🛻</button>
      <button type="button" class="btn">🚚</button>
      <button type="button" class="btn">🚛</button>
      <button type="button" class="btn">🚜</button>
      <button type="button" class="btn">🏎</button>
      <button type="button" class="btn">🏍</button>
      <button type="button" class="btn">🛵</button>
      <button type="button" class="btn">🦽</button>
      <button type="button" class="btn">🦼</button>
      <button type="button" class="btn">🛺</button>
      <button type="button" class="btn">🚲</button>
      <button type="button" class="btn">🛴</button>
      <button type="button" class="btn">🛹</button>
      <button type="button" class="btn">🛼</button>
      <button type="button" class="btn">🚏</button>
      <button type="button" class="btn">🛣</button>
      <button type="button" class="btn">🛤</button>
      <button type="button" class="btn">🛢</button>
      <button type="button" class="btn">⛽</button>
      <button type="button" class="btn">🚨</button>
      <button type="button" class="btn">🚥</button>
      <button type="button" class="btn">🚦</button>
      <button type="button" class="btn">🛑</button>
      <button type="button" class="btn">🚧</button>
      <button type="button" class="btn">⚓</button>
      <button type="button" class="btn">⛵</button>
      <button type="button" class="btn">🛶</button>
      <button type="button" class="btn">🚤</button>
      <button type="button" class="btn">🛳</button>
      <button type="button" class="btn">⛴</button>
      <button type="button" class="btn">🛥</button>
      <button type="button" class="btn">🚢</button>
      <button type="button" class="btn">✈</button>
      <button type="button" class="btn">🛩</button>
      <button type="button" class="btn">🛫</button>
      <button type="button" class="btn">🛬</button>
      <button type="button" class="btn">🪂</button>
      <button type="button" class="btn">💺</button>
      <button type="button" class="btn">🚁</button>
      <button type="button" class="btn">🚟</button>
      <button type="button" class="btn">🚠</button>
      <button type="button" class="btn">🚡</button>
      <button type="button" class="btn">🛰</button>
      <button type="button" class="btn">🚀</button>
      <button type="button" class="btn">🛸</button>
      <button type="button" class="btn">🛎</button>
      <button type="button" class="btn">🧳</button>
      <button type="button" class="btn">⌛</button>
      <button type="button" class="btn">⏳</button>
      <button type="button" class="btn">⌚</button>
      <button type="button" class="btn">⏰</button>
      <button type="button" class="btn">⏱</button>
      <button type="button" class="btn">⏲</button>
      <button type="button" class="btn">🕰</button>
      <button type="button" class="btn">🕛</button>
      <button type="button" class="btn">🕧</button>
      <button type="button" class="btn">🕐</button>
      <button type="button" class="btn">🕜</button>
      <button type="button" class="btn">🕑</button>
      <button type="button" class="btn">🕝</button>
      <button type="button" class="btn">🕒</button>
      <button type="button" class="btn">🕞</button>
      <button type="button" class="btn">🕓</button>
      <button type="button" class="btn">🕟</button>
      <button type="button" class="btn">🕔</button>
      <button type="button" class="btn">🕠</button>
      <button type="button" class="btn">🕕</button>
      <button type="button" class="btn">🕡</button>
      <button type="button" class="btn">🕖</button>
      <button type="button" class="btn">🕢</button>
      <button type="button" class="btn">🕗</button>
      <button type="button" class="btn">🕣</button>
      <button type="button" class="btn">🕘</button>
      <button type="button" class="btn">🕤</button>
      <button type="button" class="btn">🕙</button>
      <button type="button" class="btn">🕥</button>
      <button type="button" class="btn">🕚</button>
      <button type="button" class="btn">🕦</button>
      <button type="button" class="btn">🌑</button>
      <button type="button" class="btn">🌒</button>
      <button type="button" class="btn">🌓</button>
      <button type="button" class="btn">🌔</button>
      <button type="button" class="btn">🌕</button>
      <button type="button" class="btn">🌖</button>
      <button type="button" class="btn">🌗</button>
      <button type="button" class="btn">🌘</button>
      <button type="button" class="btn">🌙</button>
      <button type="button" class="btn">🌚</button>
      <button type="button" class="btn">🌛</button>
      <button type="button" class="btn">🌜</button>
      <button type="button" class="btn">🌡</button>
      <button type="button" class="btn">☀</button>
      <button type="button" class="btn">🌝</button>
      <button type="button" class="btn">🌞</button>
      <button type="button" class="btn">🪐</button>
      <button type="button" class="btn">⭐</button>
      <button type="button" class="btn">🌟</button>
      <button type="button" class="btn">🌠</button>
      <button type="button" class="btn">🌌</button>
      <button type="button" class="btn">☁</button>
      <button type="button" class="btn">⛅</button>
      <button type="button" class="btn">⛈</button>
      <button type="button" class="btn">🌤</button>
      <button type="button" class="btn">🌥</button>
      <button type="button" class="btn">🌦</button>
      <button type="button" class="btn">🌧</button>
      <button type="button" class="btn">🌨</button>
      <button type="button" class="btn">🌩</button>
      <button type="button" class="btn">🌪</button>
      <button type="button" class="btn">🌫</button>
      <button type="button" class="btn">🌬</button>
      <button type="button" class="btn">🌀</button>
      <button type="button" class="btn">🌈</button>
      <button type="button" class="btn">🌂</button>
      <button type="button" class="btn">☂</button>
      <button type="button" class="btn">☔</button>
      <button type="button" class="btn">⛱</button>
      <button type="button" class="btn">⚡</button>
      <button type="button" class="btn">❄</button>
      <button type="button" class="btn">☃</button>
      <button type="button" class="btn">⛄</button>
      <button type="button" class="btn">☄</button>
      <button type="button" class="btn">🔥</button>
      <button type="button" class="btn">💧</button>
      <button type="button" class="btn">🌊</button>
      <button type="button" class="btn">🎃</button>
      <button type="button" class="btn">🎄</button>
      <button type="button" class="btn">🎆</button>
      <button type="button" class="btn">🎇</button>
      <button type="button" class="btn">🧨</button>
      <button type="button" class="btn">✨</button>
      <button type="button" class="btn">🎈</button>
      <button type="button" class="btn">🎉</button>
      <button type="button" class="btn">🎊</button>
      <button type="button" class="btn">🎋</button>
      <button type="button" class="btn">🎍</button>
      <button type="button" class="btn">🎎</button>
      <button type="button" class="btn">🎏</button>
      <button type="button" class="btn">🎐</button>
      <button type="button" class="btn">🎑</button>
      <button type="button" class="btn">🧧</button>
      <button type="button" class="btn">🎀</button>
      <button type="button" class="btn">🎁</button>
      <button type="button" class="btn">🎗</button>
      <button type="button" class="btn">🎟</button>
      <button type="button" class="btn">🎫</button>
      <button type="button" class="btn">🎖</button>
      <button type="button" class="btn">🏆</button>
      <button type="button" class="btn">🏅</button>
      <button type="button" class="btn">🥇</button>
      <button type="button" class="btn">🥈</button>
      <button type="button" class="btn">🥉</button>
      <button type="button" class="btn">⚽</button>
      <button type="button" class="btn">⚾</button>
      <button type="button" class="btn">🥎</button>
      <button type="button" class="btn">🏀</button>
      <button type="button" class="btn">🏐</button>
      <button type="button" class="btn">🏈</button>
      <button type="button" class="btn">🏉</button>
      <button type="button" class="btn">🎾</button>
      <button type="button" class="btn">🥏</button>
      <button type="button" class="btn">🎳</button>
      <button type="button" class="btn">🏏</button>
      <button type="button" class="btn">🏑</button>
      <button type="button" class="btn">🏒</button>
      <button type="button" class="btn">🥍</button>
      <button type="button" class="btn">🏓</button>
      <button type="button" class="btn">🏸</button>
      <button type="button" class="btn">🥊</button>
      <button type="button" class="btn">🥋</button>
      <button type="button" class="btn">🥅</button>
      <button type="button" class="btn">⛳</button>
      <button type="button" class="btn">⛸</button>
      <button type="button" class="btn">🎣</button>
      <button type="button" class="btn">🤿</button>
      <button type="button" class="btn">🎽</button>
      <button type="button" class="btn">🎿</button>
      <button type="button" class="btn">🛷</button>
      <button type="button" class="btn">🥌</button>
      <button type="button" class="btn">🎯</button>
      <button type="button" class="btn">🪀</button>
      <button type="button" class="btn">🪁</button>
      <button type="button" class="btn">🎱</button>
      <button type="button" class="btn">🔮</button>
      <button type="button" class="btn">🪄</button>
      <button type="button" class="btn">🧿</button>
      <button type="button" class="btn">🎮</button>
      <button type="button" class="btn">🕹</button>
      <button type="button" class="btn">🎰</button>
      <button type="button" class="btn">🎲</button>
      <button type="button" class="btn">🧩</button>
      <button type="button" class="btn">🧸</button>
      <button type="button" class="btn">🪅</button>
      <button type="button" class="btn">🪆</button>
      <button type="button" class="btn">♠</button>
      <button type="button" class="btn">♥</button>
      <button type="button" class="btn">♦</button>
      <button type="button" class="btn">♣</button>
      <button type="button" class="btn">♟</button>
      <button type="button" class="btn">🃏</button>
      <button type="button" class="btn">🀄</button>
      <button type="button" class="btn">🎴</button>
      <button type="button" class="btn">🎭</button>
      <button type="button" class="btn">🖼</button>
      <button type="button" class="btn">🎨</button>
      <button type="button" class="btn">🧵</button>
      <button type="button" class="btn">🪡</button>
      <button type="button" class="btn">🧶</button>
      <button type="button" class="btn">🪢</button>
      <button type="button" class="btn">👓</button>
      <button type="button" class="btn">🕶</button>
      <button type="button" class="btn">🥽</button>
      <button type="button" class="btn">🥼</button>
      <button type="button" class="btn">🦺</button>
      <button type="button" class="btn">👔</button>
      <button type="button" class="btn">👕</button>
      <button type="button" class="btn">👖</button>
      <button type="button" class="btn">🧣</button>
      <button type="button" class="btn">🧤</button>
      <button type="button" class="btn">🧥</button>
      <button type="button" class="btn">🧦</button>
      <button type="button" class="btn">👗</button>
      <button type="button" class="btn">👘</button>
      <button type="button" class="btn">🥻</button>
      <button type="button" class="btn">🩱</button>
      <button type="button" class="btn">🩲</button>
      <button type="button" class="btn">🩳</button>
      <button type="button" class="btn">👙</button>
      <button type="button" class="btn">👚</button>
      <button type="button" class="btn">👛</button>
      <button type="button" class="btn">👜</button>
      <button type="button" class="btn">👝</button>
      <button type="button" class="btn">🛍</button>
      <button type="button" class="btn">🎒</button>
      <button type="button" class="btn">🩴</button>
      <button type="button" class="btn">👞</button>
      <button type="button" class="btn">👟</button>
      <button type="button" class="btn">🥾</button>
      <button type="button" class="btn">🥿</button>
      <button type="button" class="btn">👠</button>
      <button type="button" class="btn">👡</button>
      <button type="button" class="btn">🩰</button>
      <button type="button" class="btn">👢</button>
      <button type="button" class="btn">👑</button>
      <button type="button" class="btn">👒</button>
      <button type="button" class="btn">🎩</button>
      <button type="button" class="btn">🎓</button>
      <button type="button" class="btn">🧢</button>
      <button type="button" class="btn">🪖</button>
      <button type="button" class="btn">⛑</button>
      <button type="button" class="btn">📿</button>
      <button type="button" class="btn">💄</button>
      <button type="button" class="btn">💍</button>
      <button type="button" class="btn">💎</button>
      <button type="button" class="btn">🔇</button>
      <button type="button" class="btn">🔈</button>
      <button type="button" class="btn">🔉</button>
      <button type="button" class="btn">🔊</button>
      <button type="button" class="btn">📢</button>
      <button type="button" class="btn">📣</button>
      <button type="button" class="btn">📯</button>
      <button type="button" class="btn">🔔</button>
      <button type="button" class="btn">🔕</button>
      <button type="button" class="btn">🎼</button>
      <button type="button" class="btn">🎵</button>
      <button type="button" class="btn">🎶</button>
      <button type="button" class="btn">🎙</button>
      <button type="button" class="btn">🎚</button>
      <button type="button" class="btn">🎛</button>
      <button type="button" class="btn">🎤</button>
      <button type="button" class="btn">🎧</button>
      <button type="button" class="btn">📻</button>
      <button type="button" class="btn">🎷</button>
      <button type="button" class="btn">🪗</button>
      <button type="button" class="btn">🎸</button>
      <button type="button" class="btn">🎹</button>
      <button type="button" class="btn">🎺</button>
      <button type="button" class="btn">🎻</button>
      <button type="button" class="btn">🪕</button>
      <button type="button" class="btn">🥁</button>
      <button type="button" class="btn">🪘</button>
      <button type="button" class="btn">📱</button>
      <button type="button" class="btn">📲</button>
      <button type="button" class="btn">☎</button>
      <button type="button" class="btn">📞</button>
      <button type="button" class="btn">📟</button>
      <button type="button" class="btn">📠</button>
      <button type="button" class="btn">🔋</button>
      <button type="button" class="btn">🔌</button>
      <button type="button" class="btn">💻</button>
      <button type="button" class="btn">🖥</button>
      <button type="button" class="btn">🖨</button>
      <button type="button" class="btn">⌨</button>
      <button type="button" class="btn">🖱</button>
      <button type="button" class="btn">🖲</button>
      <button type="button" class="btn">💽</button>
      <button type="button" class="btn">💾</button>
      <button type="button" class="btn">💿</button>
      <button type="button" class="btn">📀</button>
      <button type="button" class="btn">🧮</button>
      <button type="button" class="btn">🎥</button>
      <button type="button" class="btn">🎞</button>
      <button type="button" class="btn">📽</button>
      <button type="button" class="btn">🎬</button>
      <button type="button" class="btn">📺</button>
      <button type="button" class="btn">📷</button>
      <button type="button" class="btn">📸</button>
      <button type="button" class="btn">📹</button>
      <button type="button" class="btn">📼</button>
      <button type="button" class="btn">🔍</button>
      <button type="button" class="btn">🔎</button>
      <button type="button" class="btn">🕯</button>
      <button type="button" class="btn">💡</button>
      <button type="button" class="btn">🔦</button>
      <button type="button" class="btn">🏮</button>
      <button type="button" class="btn">🪔</button>
      <button type="button" class="btn">📔</button>
      <button type="button" class="btn">📕</button>
      <button type="button" class="btn">📖</button>
      <button type="button" class="btn">📗</button>
      <button type="button" class="btn">📘</button>
      <button type="button" class="btn">📙</button>
      <button type="button" class="btn">📚</button>
      <button type="button" class="btn">📓</button>
      <button type="button" class="btn">📒</button>
      <button type="button" class="btn">📃</button>
      <button type="button" class="btn">📜</button>
      <button type="button" class="btn">📄</button>
      <button type="button" class="btn">📰</button>
      <button type="button" class="btn">🗞</button>
      <button type="button" class="btn">📑</button>
      <button type="button" class="btn">🔖</button>
      <button type="button" class="btn">🏷</button>
      <button type="button" class="btn">💰</button>
      <button type="button" class="btn">🪙</button>
      <button type="button" class="btn">💴</button>
      <button type="button" class="btn">💵</button>
      <button type="button" class="btn">💶</button>
      <button type="button" class="btn">💷</button>
      <button type="button" class="btn">💸</button>
      <button type="button" class="btn">💳</button>
      <button type="button" class="btn">🧾</button>
      <button type="button" class="btn">💹</button>
      <button type="button" class="btn">✉</button>
      <button type="button" class="btn">📧</button>
      <button type="button" class="btn">📨</button>
      <button type="button" class="btn">📩</button>
      <button type="button" class="btn">📤</button>
      <button type="button" class="btn">📥</button>
      <button type="button" class="btn">📦</button>
      <button type="button" class="btn">📫</button>
      <button type="button" class="btn">📪</button>
      <button type="button" class="btn">📬</button>
      <button type="button" class="btn">📭</button>
      <button type="button" class="btn">📮</button>
      <button type="button" class="btn">🗳</button>
      <button type="button" class="btn">✏</button>
      <button type="button" class="btn">✒</button>
      <button type="button" class="btn">🖋</button>
      <button type="button" class="btn">🖊</button>
      <button type="button" class="btn">🖌</button>
      <button type="button" class="btn">🖍</button>
      <button type="button" class="btn">📝</button>
      <button type="button" class="btn">💼</button>
      <button type="button" class="btn">📁</button>
      <button type="button" class="btn">📂</button>
      <button type="button" class="btn">🗂</button>
      <button type="button" class="btn">📅</button>
      <button type="button" class="btn">📆</button>
      <button type="button" class="btn">🗒</button>
      <button type="button" class="btn">🗓</button>
      <button type="button" class="btn">📇</button>
      <button type="button" class="btn">📈</button>
      <button type="button" class="btn">📉</button>
      <button type="button" class="btn">📊</button>
      <button type="button" class="btn">📋</button>
      <button type="button" class="btn">📌</button>
      <button type="button" class="btn">📍</button>
      <button type="button" class="btn">📎</button>
      <button type="button" class="btn">🖇</button>
      <button type="button" class="btn">📏</button>
      <button type="button" class="btn">📐</button>
      <button type="button" class="btn">✂</button>
      <button type="button" class="btn">🗃</button>
      <button type="button" class="btn">🗄</button>
      <button type="button" class="btn">🗑</button>
      <button type="button" class="btn">🔒</button>
      <button type="button" class="btn">🔓</button>
      <button type="button" class="btn">🔏</button>
      <button type="button" class="btn">🔐</button>
      <button type="button" class="btn">🔑</button>
      <button type="button" class="btn">🗝</button>
      <button type="button" class="btn">🔨</button>
      <button type="button" class="btn">🪓</button>
      <button type="button" class="btn">⛏</button>
      <button type="button" class="btn">⚒</button>
      <button type="button" class="btn">🛠</button>
      <button type="button" class="btn">🗡</button>
      <button type="button" class="btn">⚔</button>
      <button type="button" class="btn">🔫</button>
      <button type="button" class="btn">🪃</button>
      <button type="button" class="btn">🏹</button>
      <button type="button" class="btn">🛡</button>
      <button type="button" class="btn">🪚</button>
      <button type="button" class="btn">🔧</button>
      <button type="button" class="btn">🪛</button>
      <button type="button" class="btn">🔩</button>
      <button type="button" class="btn">⚙</button>
      <button type="button" class="btn">🗜</button>
      <button type="button" class="btn">⚖</button>
      <button type="button" class="btn">🦯</button>
      <button type="button" class="btn">🔗</button>
      <button type="button" class="btn">⛓</button>
      <button type="button" class="btn">🪝</button>
      <button type="button" class="btn">🧰</button>
      <button type="button" class="btn">🧲</button>
      <button type="button" class="btn">🪜</button>
      <button type="button" class="btn">⚗</button>
      <button type="button" class="btn">🧪</button>
      <button type="button" class="btn">🧫</button>
      <button type="button" class="btn">🧬</button>
      <button type="button" class="btn">🔬</button>
      <button type="button" class="btn">🔭</button>
      <button type="button" class="btn">📡</button>
      <button type="button" class="btn">💉</button>
      <button type="button" class="btn">🩸</button>
      <button type="button" class="btn">💊</button>
      <button type="button" class="btn">🩹</button>
      <button type="button" class="btn">🩺</button>
      <button type="button" class="btn">🚪</button>
      <button type="button" class="btn">🛗</button>
      <button type="button" class="btn">🪞</button>
      <button type="button" class="btn">🪟</button>
      <button type="button" class="btn">🛏</button>
      <button type="button" class="btn">🛋</button>
      <button type="button" class="btn">🪑</button>
      <button type="button" class="btn">🚽</button>
      <button type="button" class="btn">🪠</button>
      <button type="button" class="btn">🚿</button>
      <button type="button" class="btn">🛁</button>
      <button type="button" class="btn">🪤</button>
      <button type="button" class="btn">🪒</button>
      <button type="button" class="btn">🧴</button>
      <button type="button" class="btn">🧷</button>
      <button type="button" class="btn">🧹</button>
      <button type="button" class="btn">🧺</button>
      <button type="button" class="btn">🧻</button>
      <button type="button" class="btn">🪣</button>
      <button type="button" class="btn">🧼</button>
      <button type="button" class="btn">🪥</button>
      <button type="button" class="btn">🧽</button>
      <button type="button" class="btn">🧯</button>
      <button type="button" class="btn">🛒</button>
      <button type="button" class="btn">🚬</button>
      <button type="button" class="btn">⚰</button>
      <button type="button" class="btn">🪦</button>
      <button type="button" class="btn">⚱</button>
      <button type="button" class="btn">🗿</button>
      <button type="button" class="btn">🪧</button>
      <button type="button" class="btn">🏧</button>
      <button type="button" class="btn">🚮</button>
      <button type="button" class="btn">🚰</button>
      <button type="button" class="btn">♿</button>
      <button type="button" class="btn">🚹</button>
      <button type="button" class="btn">🚺</button>
      <button type="button" class="btn">🚻</button>
      <button type="button" class="btn">🚼</button>
      <button type="button" class="btn">🚾</button>
      <button type="button" class="btn">🛂</button>
      <button type="button" class="btn">🛃</button>
      <button type="button" class="btn">🛄</button>
      <button type="button" class="btn">🛅</button>
      <button type="button" class="btn">⚠</button>
      <button type="button" class="btn">🚸</button>
      <button type="button" class="btn">⛔</button>
      <button type="button" class="btn">🚫</button>
      <button type="button" class="btn">🚳</button>
      <button type="button" class="btn">🚭</button>
      <button type="button" class="btn">🚯</button>
      <button type="button" class="btn">🚱</button>
      <button type="button" class="btn">🚷</button>
      <button type="button" class="btn">📵</button>
      <button type="button" class="btn">🔞</button>
      <button type="button" class="btn">☢</button>
      <button type="button" class="btn">☣</button>
      <button type="button" class="btn">⬆</button>
      <button type="button" class="btn">↗</button>
      <button type="button" class="btn">➡</button>
      <button type="button" class="btn">↘</button>
      <button type="button" class="btn">⬇</button>
      <button type="button" class="btn">↙</button>
      <button type="button" class="btn">⬅</button>
      <button type="button" class="btn">↖</button>
      <button type="button" class="btn">↕</button>
      <button type="button" class="btn">↔</button>
      <button type="button" class="btn">↩</button>
      <button type="button" class="btn">↪</button>
      <button type="button" class="btn">⤴</button>
      <button type="button" class="btn">⤵</button>
      <button type="button" class="btn">🔃</button>
      <button type="button" class="btn">🔄</button>
      <button type="button" class="btn">🔙</button>
      <button type="button" class="btn">🔚</button>
      <button type="button" class="btn">🔛</button>
      <button type="button" class="btn">🔜</button>
      <button type="button" class="btn">🔝</button>
      <button type="button" class="btn">🛐</button>
      <button type="button" class="btn">⚛</button>
      <button type="button" class="btn">🕉</button>
      <button type="button" class="btn">✡</button>
      <button type="button" class="btn">☸</button>
      <button type="button" class="btn">☯</button>
      <button type="button" class="btn">✝</button>
      <button type="button" class="btn">☦</button>
      <button type="button" class="btn">☪</button>
      <button type="button" class="btn">☮</button>
      <button type="button" class="btn">🕎</button>
      <button type="button" class="btn">🔯</button>
      <button type="button" class="btn">♈</button>
      <button type="button" class="btn">♉</button>
      <button type="button" class="btn">♊</button>
      <button type="button" class="btn">♋</button>
      <button type="button" class="btn">♌</button>
      <button type="button" class="btn">♍</button>
      <button type="button" class="btn">♎</button>
      <button type="button" class="btn">♏</button>
      <button type="button" class="btn">♐</button>
      <button type="button" class="btn">♑</button>
      <button type="button" class="btn">♒</button>
      <button type="button" class="btn">♓</button>
      <button type="button" class="btn">⛎</button>
      <button type="button" class="btn">🔀</button>
      <button type="button" class="btn">🔁</button>
      <button type="button" class="btn">🔂</button>
      <button type="button" class="btn">▶</button>
      <button type="button" class="btn">⏩</button>
      <button type="button" class="btn">⏭</button>
      <button type="button" class="btn">⏯</button>
      <button type="button" class="btn">◀</button>
      <button type="button" class="btn">⏪</button>
      <button type="button" class="btn">⏮</button>
      <button type="button" class="btn">🔼</button>
      <button type="button" class="btn">⏫</button>
      <button type="button" class="btn">🔽</button>
      <button type="button" class="btn">⏬</button>
      <button type="button" class="btn">⏸</button>
      <button type="button" class="btn">⏹</button>
      <button type="button" class="btn">⏺</button>
      <button type="button" class="btn">⏏</button>
      <button type="button" class="btn">🎦</button>
      <button type="button" class="btn">🔅</button>
      <button type="button" class="btn">🔆</button>
      <button type="button" class="btn">📶</button>
      <button type="button" class="btn">📳</button>
      <button type="button" class="btn">📴</button>
      <button type="button" class="btn">♀</button>
      <button type="button" class="btn">♂</button>
      <button type="button" class="btn">⚧</button>
      <button type="button" class="btn">✖</button>
      <button type="button" class="btn">➕</button>
      <button type="button" class="btn">➖</button>
      <button type="button" class="btn">➗</button>
      <button type="button" class="btn">♾</button>
      <button type="button" class="btn">‼</button>
      <button type="button" class="btn">⁉</button>
      <button type="button" class="btn">❓</button>
      <button type="button" class="btn">❔</button>
      <button type="button" class="btn">❕</button>
      <button type="button" class="btn">❗</button>
      <button type="button" class="btn">〰</button>
      <button type="button" class="btn">💱</button>
      <button type="button" class="btn">💲</button>
      <button type="button" class="btn">⚕</button>
      <button type="button" class="btn">♻</button>
      <button type="button" class="btn">⚜</button>
      <button type="button" class="btn">🔱</button>
      <button type="button" class="btn">📛</button>
      <button type="button" class="btn">🔰</button>
      <button type="button" class="btn">⭕</button>
      <button type="button" class="btn">✅</button>
      <button type="button" class="btn">☑</button>
      <button type="button" class="btn">✔</button>
      <button type="button" class="btn">❌</button>
      <button type="button" class="btn">❎</button>
      <button type="button" class="btn">➰</button>
      <button type="button" class="btn">➿</button>
      <button type="button" class="btn">〽</button>
      <button type="button" class="btn">✳</button>
      <button type="button" class="btn">✴</button>
      <button type="button" class="btn">❇</button>
      <button type="button" class="btn">©</button>
      <button type="button" class="btn">®</button>
      <button type="button" class="btn">™</button>
      <button type="button" class="btn">🔠</button>
      <button type="button" class="btn">🔡</button>
      <button type="button" class="btn">🔢</button>
      <button type="button" class="btn">🔣</button>
      <button type="button" class="btn">🔤</button>
      <button type="button" class="btn">🅰</button>
      <button type="button" class="btn">🆎</button>
      <button type="button" class="btn">🅱</button>
      <button type="button" class="btn">🆑</button>
      <button type="button" class="btn">🆒</button>
      <button type="button" class="btn">🆓</button>
      <button type="button" class="btn">ℹ</button>
      <button type="button" class="btn">🆔</button>
      <button type="button" class="btn">Ⓜ</button>
      <button type="button" class="btn">🆕</button>
      <button type="button" class="btn">🆖</button>
      <button type="button" class="btn">🅾</button>
      <button type="button" class="btn">🆗</button>
      <button type="button" class="btn">🅿</button>
      <button type="button" class="btn">🆘</button>
      <button type="button" class="btn">🆙</button>
      <button type="button" class="btn">🆚</button>
      <button type="button" class="btn">🈁</button>
      <button type="button" class="btn">🈂</button>
      <button type="button" class="btn">🈷</button>
      <button type="button" class="btn">🈶</button>
      <button type="button" class="btn">🈯</button>
      <button type="button" class="btn">🉐</button>
      <button type="button" class="btn">🈹</button>
      <button type="button" class="btn">🈚</button>
      <button type="button" class="btn">🈲</button>
      <button type="button" class="btn">🉑</button>
      <button type="button" class="btn">🈸</button>
      <button type="button" class="btn">🈴</button>
      <button type="button" class="btn">🈳</button>
      <button type="button" class="btn">㊗</button>
      <button type="button" class="btn">㊙</button>
      <button type="button" class="btn">🈺</button>
      <button type="button" class="btn">🈵</button>
      <button type="button" class="btn">🔴</button>
      <button type="button" class="btn">🟠</button>
      <button type="button" class="btn">🟡</button>
      <button type="button" class="btn">🟢</button>
      <button type="button" class="btn">🔵</button>
      <button type="button" class="btn">🟣</button>
      <button type="button" class="btn">🟤</button>
      <button type="button" class="btn">⚫</button>
      <button type="button" class="btn">⚪</button>
      <button type="button" class="btn">🟥</button>
      <button type="button" class="btn">🟧</button>
      <button type="button" class="btn">🟨</button>
      <button type="button" class="btn">🟩</button>
      <button type="button" class="btn">🟦</button>
      <button type="button" class="btn">🟪</button>
      <button type="button" class="btn">🟫</button>
      <button type="button" class="btn">⬛</button>
      <button type="button" class="btn">⬜</button>
      <button type="button" class="btn">◼</button>
      <button type="button" class="btn">◻</button>
      <button type="button" class="btn">◾</button>
      <button type="button" class="btn">◽</button>
      <button type="button" class="btn">▪</button>
      <button type="button" class="btn">▫</button>
      <button type="button" class="btn">🔶</button>
      <button type="button" class="btn">🔷</button>
      <button type="button" class="btn">🔸</button>
      <button type="button" class="btn">🔹</button>
      <button type="button" class="btn">🔺</button>
      <button type="button" class="btn">🔻</button>
      <button type="button" class="btn">💠</button>
      <button type="button" class="btn">🔘</button>
      <button type="button" class="btn">🔳</button>
      <button type="button" class="btn">🔲</button>
      <button type="button" class="btn">🏁</button>
      <button type="button" class="btn">🚩</button>
      <button type="button" class="btn">🎌</button>
      <button type="button" class="btn">🏴</button>
      <button type="button" class="btn">🏳</button>
    </div>
  </div>
</template>
<script setup>
import { defineProps, defineEmits, onMounted, onUnmounted, ref } from 'vue';
const emojiListWrap = ref(null);
const emit = defineEmits(['emoji-click', 'emoji-toggle']);

const props = defineProps({
  showToggle: {
    Type: Boolean,
    default: false,
  },
});

const btnClickEnventHandler = event => {
  if (event.target && event.target.tagName === 'BUTTON') {
    const text = event.target.innerText;
    // 또는 다른 작업을 수행합니다.
    emit('emoji-click', text);
  }
};

const clickOutsideHandler = event => {
  if (
    event.target.id != 'emojiBtn' &&
    !emojiListWrap.value.contains(event.target)
  ) {
    emit('emoji-toggle', false);
  }
};

// 이벤트 핸들러 등록
onMounted(() => {
  emojiListWrap.value = document.querySelector('.emoji-list-wrap');
  document.addEventListener('click', clickOutsideHandler);
});

// 이벤트 핸들러 제거
onUnmounted(() => {
  document.removeEventListener('click', clickOutsideHandler);
});
</script>
<style lang="scss" scoped>
.emoji-list-wrap {
  position: absolute;
  top: -500px;
  right: 0;
  max-width: 480px;
  height: 500px;
  background: rgb(29, 29, 29);
  z-index: 999;
  overflow-y: scroll;
  border-top-left-radius: 15px;
  padding: 5px;

  &::-webkit-scrollbar {
    width: 15px; /* 스크롤바의 너비 */
  }

  &:hover::-webkit-scrollbar-thumb {
    background: #696969; /* 스크롤바의 색상 */
    border-radius: 5px;
  }

  &::-webkit-scrollbar-track {
    // background: #595959; /*스크롤바 뒷 배경 색상*/
  }

  & .emoji-list {
    & button {
      text-align: center;
      font-size: 28px;
      width: 40px;
      height: 40px;
      padding: 0;
      background: #595959;
      margin: 5px;
      transition: transform 0.1s;

      &:hover {
        transform: scale(1.3);
      }
    }
  }
}
</style>
